# Generated by Django 4.1.5 on 2023-01-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timerlog_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerlog',
            old_name='end_timer',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='timerlog',
            old_name='start_timer',
            new_name='start_time',
        ),
    ]
